# pull official base image
FROM node:12.13.0-alpine

# set working directory
WORKDIR /usr/src/app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install app dependencies
# Copies package.json and package-lock.json to Docker environment
COPY package*.json ./

# Installs all node packages
RUN npm install 

# Copies everything over to Docker environment
COPY . .

EXPOSE 3000

# Start app
CMD ["npm", "start"]